# Generated by Django 6.0 on 2025-12-15 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent'), ('buy', 'Buy')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_photo', models.ImageField(upload_to='listings/')),
                ('photo_1', models.ImageField(upload_to='listings/')),
                ('photo_2', models.ImageField(upload_to='listings/')),
                ('photo_3', models.ImageField(upload_to='listings/')),
                ('is_published', models.BooleanField(default=False)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
