# Generated by Django 6.0 on 2026-01-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('FOR_SALE', 'For Sale'), ('FOR_RENT', 'For Rent')], default='FOR_SALE', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
    ]
