# Generated by Django 6.0 on 2026-01-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_category_alter_listing_photo_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
